name: CreateRelease

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Pushing
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'OneMorRockgrove'

      - name: Zip release
        run: 7z a OneMorRockgrove.zip * -xr!*.git* -x!changelog.txt -x!README.md


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: OneMorRockgrove.zip